export default {
  hud_political_capital: require('/assets/icons/hud/political_capital.svg'),
  hud_extinction_rate: require('/assets/icons/hud/extinction.svg'),
  hud_contentedness: require('/assets/icons/hud/contentedness.svg'),
  hud_warming: require('/assets/icons/hud/warming.svg'),
  political_capital: require('/assets/icons/pips/political_capital.png'),
  contentedness: require('/assets/icons/contentedness.png'),
  emissions: require('/assets/icons/emissions.png'),
  warming: require('/assets/icons/warming.png'),
  extinction_rate: require('/assets/icons/extinction.png'),
  temperature: require('/assets/icons/temperature.svg'),
  biodiversity: require('/assets/icons/extinction.png'),
  precipitation: require('/assets/icons/precipitation.svg'),
  land: require('/assets/icons/land.png'),
  energy: require('/assets/icons/energy.png'),
  labor: require('/assets/icons/labor.png'),
  water: require('/assets/icons/water.png'),
  power: require('/assets/icons/pips/power.png'),
  food: require('/assets/icons/pips/food.png'),
  improve: require('/assets/placeholders/improve.svg'),
  worsen: require('/assets/placeholders/worsen.svg'),
  steady: require('/assets/icons/steady.svg'),
  research: require('/assets/icons/pips/research.png'),
  initiative: require('/assets/icons/pips/initiative.png'),
  policy: require('/assets/icons/pips/political_capital.png'),
  population: require('/assets/icons/population.png'),
  demand: require('/assets/icons/demand.png'),
  output: require('/assets/icons/output.png'),
  fuel: require('/assets/icons/fuel.png'),
  electricity: require('/assets/icons/electricity.png'),
  plantcalories: require('/assets/icons/plantcalories.png'),
  animalcalories: require('/assets/icons/animalcalories.png'),
  plant_calories: require('/assets/icons/plantcalories.png'),
  animal_calories: require('/assets/icons/animalcalories.png'),
  unlocks: require('/assets/icons/unlocks.png'),
  cost: require('/assets/icons/cost.png'),
  ban: require('/assets/icons/ban.png'),
  implement: require('/assets/icons/implement.png'),
  request: require('/assets/icons/request.png'),
  chance: require('/assets/icons/chance.png'),
  protect: require('/assets/icons/protect.png'),
  wealth: require('/assets/icons/wealth.png'),
  habitability: require('/assets/icons/habitability.png'),
  relationship: require('/assets/icons/relationship.png'),
  relationship_empty: require('/assets/icons/relationship_empty.png'),
  add: require('/assets/icons/add.svg'),
  check: require('/assets/icons/check.png'),
  check_blk: require('/assets/icons/check_blk.png'),
  closed_borders: require('/assets/icons/ban.png'),
  development: require('/assets/icons/development.png'),
  degrowth: require('/assets/icons/degrowth.png'),
  car: require('/assets/icons/car.png'),
  ocean: require('/assets/icons/ocean.png'),
  sound: require('/assets/icons/sound.png'),
  no_sound: require('/assets/icons/no_sound.png'),
  mix_token: require('/assets/icons/mix_allocation.png'),
  alert: require('/assets/icons/alert.png'),
  halted: require('/assets/icons/halted.png'),
  down_arrow: require('/assets/icons/down_arrow.png'),
  down_arrow_small: require('/assets/icons/down_arrow.svg'),
  hourglass: require('/assets/icons/hourglass.svg'),
  sea_level_rise: require('/assets/icons/sea_level_rise.png'),
  arrow_right: require('/assets/icons/arrow_right.svg'),
  arrow_left: require('/assets/icons/arrow_left.svg'),
  settings: require('/assets/icons/settings.svg'),
  time: require('/assets/icons/time.svg'),
  warning: require('/assets/icons/warning.svg'),
  help: require('/assets/icons/help.svg'),

  // NPC relationships
  ally: require('/assets/icons/npcs/ally.svg'),
  neutral: require('/assets/icons/npcs/neutral.svg'),
  friendly: require('/assets/icons/npcs/friendly.svg'),
  nemesis: require('/assets/icons/npcs/nemesis.svg'),

  // Cards
  info: require('/assets/placeholders/info.svg'),
  flip: require('/assets/placeholders/flip.svg'),

  // Industries
  aviation: require('/assets/icons/industries/aviation.png'),
  buildings: require('/assets/icons/industries/buildings.png'),
  chemicals: require('/assets/icons/industries/chemicals.png'),
  concrete: require('/assets/icons/industries/concrete.png'),
  iron_and_steel: require('/assets/icons/industries/iron_and_steel.png'),
  other_industry: require('/assets/icons/industries/other_industry.png'),
  road_transport: require('/assets/icons/industries/road_transport.png'),
  shipping: require('/assets/icons/industries/shipping.png'),

  // Characters
  'The Authoritarian': require('/assets/characters/The Authoritarian.png'),
  'The Economist': require('/assets/characters/The Economist.png'),
  'The Technocrat': require('/assets/characters/The Technocrat.png'),
  'The Scientist': require('/assets/characters/The Scientist.png'),
  'The Populist': require('/assets/characters/The Populist.png'),
  'The Ecologist': require('/assets/characters/The Ecologist.png'),
  'The Malthusian': require('/assets/placeholders/character_placeholder.png'),
  'The Geoengineer': require('/assets/placeholders/character_placeholder.png'),
  'The Posadist': require('/assets/placeholders/character_placeholder.png'),
  'The Wretched': require('/assets/placeholders/character_placeholder.png'),
  'The Consumerist': require('/assets/placeholders/character_placeholder.png'),
  'The Half-Earth Socialist': require('/assets/placeholders/character_placeholder.png'),
  'The Fully-Automated Luxury Communist': require('/assets/placeholders/character_placeholder.png'),
  'The Agronomist': require('/assets/placeholders/character_placeholder.png'),

  // Feedstocks
  coal: require('/assets/icons/feedstocks/coal.png'),
  lithium: require('/assets/icons/feedstocks/lithium.png'),
  natural_gas: require('/assets/icons/feedstocks/natural_gas.png'),
  oil: require('/assets/icons/feedstocks/oil.png'),
  uranium: require('/assets/icons/feedstocks/uranium.png'),
  thorium: require('/assets/icons/feedstocks/thorium.png'),
  soil: require('/assets/icons/feedstocks/soil.png'),
  other: require('/assets/icons/feedstocks/other.png'),

  // Process features
  IsCCS: require('/assets/icons/features/is_ccs.png'),
  IsCombustion: require('/assets/icons/features/is_combustion.png'),
  IsIntermittent: require('/assets/icons/features/is_intermittent.png'),
  MakesNuclearWaste: require('/assets/icons/features/makes_nuclear_waste.png'),
  CanMeltdown: require('/assets/icons/features/can_meltdown.png'),
  IsLaborIntensive: require('/assets/icons/features/is_labor_intensive.png'),
  IsSolar: require('/assets/icons/features/is_solar.png'),
  IsFossil: require('/assets/icons/features/is_fossil.png'),
  UsesLivestock: require('/assets/icons/features/uses_livestock.png'),
  UsesPesticides: require('/assets/icons/features/uses_pesticides.png'),
  UsesSynFertilizer: require('/assets/icons/features/uses_syn_fertilizer.png'),

  // Icon events
  "heatwave__3": require('/assets/icons/pips/heatwave__3.png'),
  "wildfires": require('/assets/icons/pips/wildfires.png'),
  "famine": require('/assets/icons/pips/famine.png'),
  "resistance__2": require('/assets/icons/pips/resistance__2.png'),
  "co2_leak": require('/assets/icons/pips/co2_leak.png'),
  "flood__2": require('/assets/icons/pips/flood__2.png'),
  "power": require('/assets/icons/pips/power.png'),
  "flood": require('/assets/icons/pips/flood.png'),
  "hurricane": require('/assets/icons/pips/hurricane.png'),
  "crop_failure": require('/assets/icons/pips/crop_failure.png'),
  "disease": require('/assets/icons/pips/disease.png'),
  "attacks": require('/assets/icons/pips/attacks.png'),
  "wildfires__3": require('/assets/icons/pips/wildfires__3.png'),
  "wildfires__2": require('/assets/icons/pips/wildfires__2.png'),
  "power__2": require('/assets/icons/pips/power__2.png'),
  "resistance": require('/assets/icons/pips/resistance.png'),
  "heatwave": require('/assets/icons/pips/heatwave.png'),
  "flood__3": require('/assets/icons/pips/flood__3.png'),
  "resistance__3": require('/assets/icons/pips/resistance__3.png'),
  "heatwave__2": require('/assets/icons/pips/heatwave__2.png'),
};
