export default {
  political_capital: require('/assets/icons/pips/political_capital.png'),
  extinction_rate: require('/assets/icons/extinction.alt.png'),
  contentedness: require('/assets/icons/contentedness.png'),
  emissions: require('/assets/icons/emissions.png'),
  warming: require('/assets/icons/warming.png'),
  biodiversity: require('/assets/icons/biodiversity.png'),
  precipitation: require('/assets/icons/precipitation.png'),
  land: require('/assets/icons/land.png'),
  energy: require('/assets/icons/energy.png'),
  labor: require('/assets/icons/labor.png'),
  water: require('/assets/icons/water.png'),
  power: require('/assets/icons/pips/power.png'),
  food: require('/assets/icons/pips/food.png'),
  improve: require('/assets/placeholders/improve.svg'),
  worsen: require('/assets/placeholders/worsen.svg'),
  steady: require('/assets/icons/steady.svg'),
  research: require('/assets/icons/pips/research.png'),
  initiative: require('/assets/icons/pips/initiative.png'),
  policy: require('/assets/icons/pips/political_capital.png'),
  population: require('/assets/icons/labor.png'),
  demand: require('/assets/icons/demand.png'),
  output: require('/assets/icons/output.png'),
  fuel: require('/assets/icons/fuel.png'),
  electricity: require('/assets/icons/electricity.png'),
  plantcalories: require('/assets/icons/plantcalories.png'),
  animalcalories: require('/assets/icons/animalcalories.png'),
  plant_calories: require('/assets/icons/plantcalories.png'),
  animal_calories: require('/assets/icons/animalcalories.png'),
  unlocks: require('/assets/icons/unlocks.png'),
  cost: require('/assets/icons/cost.png'),
  ban: require('/assets/icons/ban.png'),
  implement: require('/assets/icons/implement.png'),
  request: require('/assets/icons/request.png'),
  chance: require('/assets/icons/chance.png'),
  protect: require('/assets/icons/protect.png'),
  wealth: require('/assets/icons/wealth.png'),
  habitability: require('/assets/icons/habitability.png'),
  relationship: require('/assets/icons/relationship.png'),
  relationship_empty: require('/assets/icons/relationship_empty.png'),
  add: require('/assets/icons/add.svg'),
  ally: require('/assets/icons/ally.png'),
  check: require('/assets/icons/check.png'),
  closed_borders: require('/assets/icons/ban.png'),
  car: require('/assets/icons/car.png'),
  sound: require('/assets/icons/sound.png'),
  no_sound: require('/assets/icons/no_sound.png'),
  mix_token: require('/assets/icons/mix_allocation.png'),
  alert: require('/assets/icons/alert.png'),
  halted: require('/assets/icons/halted.png'),

  // Cards
  info: require('/assets/placeholders/info.svg'),
  flip: require('/assets/placeholders/flip.svg'),

  // Industries
  aviation: require('/assets/icons/industries/aviation.png'),
  buildings: require('/assets/icons/industries/buildings.png'),
  chemicals: require('/assets/icons/industries/chemicals.png'),
  concrete: require('/assets/icons/industries/concrete.png'),
  iron_and_steel: require('/assets/icons/industries/iron_and_steel.png'),
  other_industry: require('/assets/icons/industries/other_industry.png'),
  road_transport: require('/assets/icons/industries/road_transport.png'),
  shipping: require('/assets/icons/industries/shipping.png'),

  // Characters
  'The Authoritarian': require('/assets/characters/The Authoritarian.png'),
  'The Economist': require('/assets/characters/The Economist.png'),
  'The Technocrat': require('/assets/characters/The Technocrat.png'),
  'The Scientist': require('/assets/characters/The Scientist.png'),
  'The Populist': require('/assets/characters/The Populist.png'),
  'The Ecologist': require('/assets/characters/The Ecologist.png'),
  'The Malthusian': require('/assets/placeholders/character_placeholder.png'),
  'The Geoengineer': require('/assets/placeholders/character_placeholder.png'),
  'The Posadist': require('/assets/placeholders/character_placeholder.png'),
  'The Wretched': require('/assets/placeholders/character_placeholder.png'),
  'The Consumerist': require('/assets/placeholders/character_placeholder.png'),
  'The Half-Earth Socialist': require('/assets/placeholders/character_placeholder.png'),
  'The Fully-Automated Luxury Communist': require('/assets/placeholders/character_placeholder.png'),
  'The Agronomist': require('/assets/placeholders/character_placeholder.png'),

  // Feedstocks
  coal: require('/assets/icons/feedstocks/coal.png'),
  lithium: require('/assets/icons/feedstocks/lithium.png'),
  natural_gas: require('/assets/icons/feedstocks/natural_gas.png'),
  oil: require('/assets/icons/feedstocks/oil.png'),
  uranium: require('/assets/icons/feedstocks/uranium.png'),
  thorium: require('/assets/icons/feedstocks/thorium.png'),
  soil: require('/assets/icons/feedstocks/soil.png'),
  other: require('/assets/icons/feedstocks/other.png'),

  // Process features
  is_ccs: require('/assets/icons/features/is_ccs.png'),
  is_combustion: require('/assets/icons/features/is_combustion.png'),
  is_intermittent: require('/assets/icons/features/is_intermittent.png'),
  is_intermittent: require('/assets/icons/features/is_intermittent.png'),
  is_nuclear: require('/assets/icons/features/is_nuclear.png'),
  is_solar: require('/assets/icons/features/is_solar.png'),
  is_fossil: require('/assets/icons/features/is_fossil.png'),
  uses_livestock: require('/assets/icons/features/uses_livestock.png'),
  uses_pesticides: require('/assets/icons/features/uses_pesticides.png'),
  uses_syn_fertilizer: require('/assets/icons/features/uses_syn_fertilizer.png'),
};
