// Do not edit this file. Use `parse_content.py` to regenerate it.
use crate::regions::Income;
use crate::kinds::{FeedstockMap, OutputMap};


const FEEDSTOCK_RESERVES: FeedstockMap<f32> = FeedstockMap {
    oil: 275370680000000.0,
    coal: 1.074,
    uranium: 7988600.0,
    lithium: 80000000.0,
    natural_gas: 0.0,
    soil: 0.0,
    other: 0.0
};

pub fn income_pop_change(pop: f32, income: &Income) -> f32 {
    match income {
        Income::Low => 0.02510843736506849 + -0.00027392308142168935*pop + -1.2013335809592668e-06*pop.powf(2.0) + 1.6107860430271117e-08*pop.powf(3.0),
        Income::LowerMiddle => 0.015956334414138754 + -0.00029336051833737166*pop + 7.154489844717687e-07*pop.powf(2.0) + 4.267315072469537e-09*pop.powf(3.0),
        Income::UpperMiddle => 0.007324313878541907 + -0.00021522025711188524*pop + 2.7208734051441963e-09*pop.powf(2.0) + 9.029389058532674e-09*pop.powf(3.0),
        Income::High => 0.005554574166810743 + -0.00032696397778050114*pop + 4.6328142827097576e-06*pop.powf(2.0) + -2.1135532274204256e-08*pop.powf(3.0)
    }
}

pub const OUTPUT_DEMAND: OutputMap<[f32; 4]> = OutputMap {
    electricity: [
        12.647,
        80.881867,
        368.96432,
        750.5439
    ],
    fuel: [
        84.823,
        478.748,
        1842.78168 ,
        4111.4561
    ],
    animal_calories: [
        5188.17,
        8453.8519,
        19610.3814,
        26695.9236
    ],
    plant_calories: [
        65101.22,
        69593.2533,
        73597.3736,
        75062.28
    ]
};

const LAND_LIMIT: f32 = 104000000000.0;
const WATER_LIMIT: f32 = 45500000000000000.0;
const WATER_BY_INCOME: [f32; 4] = [
    2040.4095,
    4552.624175,
    5839.79276,
    11648.18348
];
const MATERIALS_BY_INCOME: [f32; 4] = [
    2.253141687346895,
    4.3768,
    15.430,
    25.9541
];