// Do not edit this file. Use `parse_content.py` to regenerate it.
use crate::regions::Income;
use crate::kinds::{FeedstockMap, ResourceMap, OutputMap};


pub const FEEDSTOCK_RESERVES: FeedstockMap<f32> = FeedstockMap {
    oil: 624182962000000.0,
    coal: 1074000000000000000.0,
    uranium: 7988600000000.0,
    lithium: 80000000.0,
    natural_gas: 205495355718144000.0,
    soil: 1e20,
    other: 1.0,
    thorium: 5805982300000.0
};

pub const STARTING_RESOURCES: ResourceMap<f32> = ResourceMap {
    fuel: 141397300000000.0,
    electricity: 26936000000000.0,
    land: 104000000000000.0,
    water: 45500000000000000.0
};

pub fn income_pop_change(year: f32, income: &Income) -> f32 {
    match income {
        Income::Low => -137.09104615549052 + 0.20175900568502633*year + -9.881496778856683e-05*year.powf(2.0) + 1.6107860430297862e-08*year.powf(3.0),
        Income::LowerMiddle => -31.645089275035065 + 0.049053282850800455*year + -2.5144480355319464e-05*year.powf(2.0) + 4.267315072570761e-09*year.powf(3.0),
        Income::UpperMiddle => -73.97073712590549 + 0.110304344757395*year + -5.471537682118361e-05*year.powf(2.0) + 9.02938905851344e-09*year.powf(3.0),
        Income::High => 193.7774375120351 + -0.27776781135845113*year + 0.00013271413986610546*year.powf(2.0) + -2.113553227448261e-08*year.powf(3.0)
    }
}

pub const OUTPUT_DEMAND: [OutputMap<f32>; 4] = [
    OutputMap {
        fuel: 84.823,
        electricity: 12.647,
        animal_calories: 62258.01225379132,
        plant_calories: 781214.6569453699
    },
    OutputMap {
        fuel: 478.748,
        electricity: 80.881867,
        animal_calories: 101446.22307270509,
        plant_calories: 835119.0398573277
    },
    OutputMap {
        fuel: 1842.78168,
        electricity: 368.96432,
        animal_calories: 235324.57700012674,
        plant_calories: 883168.4828934266
    },
    OutputMap {
        fuel: 4111.4561,
        electricity: 750.5439,
        animal_calories: 320351.0835388199,
        plant_calories: 900747.3812494389
    }
];

pub const HYDROPOWER__LIMIT: f32 = 28470000000000.0;
pub const MATERIALS_BY_INCOME: [f32; 4] = [
    2.253141687346895,
    4.3768,
    15.430,
    25.9541
];
pub const WATER_BY_INCOME: [f32; 4] = [
    2040.4095,
    4552.624175,
    5839.79276,
    11648.18348
];